
# Note: this file's config override the Netlify UI admin config

[build]
  base = "/"
  command = "yarn workspace docusaurus-1-website netlify:build:deployPreview"
  publish = "website-1.x/build/docusaurus"

[context.deploy-preview]
  base = "/"
  command = "yarn workspace docusaurus-1-website netlify:build:deployPreview"
  publish = "website-1.x/build/docusaurus"

[context.production]
  command = "yarn workspace docusaurus-1-website netlify:build:production"
